# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='WhatMobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('samsung', 'Samsung'), ('apple', 'Apple')], db_index=True, max_length=40)),
                ('model_name', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('source_id', models.PositiveIntegerField(unique=True)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='whatmobile/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('official_price', models.CharField(blank=True, max_length=120)),
                ('official_price_value', models.IntegerField(blank=True, null=True)),
                ('official_price_currency', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('release_status', models.CharField(blank=True, max_length=120)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'model_name'],
                'indexes': [
                    models.Index(fields=['brand', 'model_name'], name='whatmobile__brand_8f1a2b_idx'),
                    models.Index(fields=['-updated_at'], name='whatmobile__updated_4c9d1e_idx'),
                ],
            },
        ),
    ]
