# Generated by Django 6.0.1 on 2026-06-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pricealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trend_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='trend_text',
            field=models.CharField(default='Stable', max_length=40),
        ),
    ]
