# Generated by Django 6.0.1 on 2026-06-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand_product_description_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedlisting',
            name='discount_pct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapedlisting',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapedlisting',
            name='source_website',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
