# Generated by Django 6.0.1 on 2026-06-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_listing_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_created_bce1a7_idx',
            old_name='products_pr_created_4b8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_brand_4bfaa4_idx',
            old_name='products_pr_brand_4c0f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_title_7d8124_idx',
            old_name='products_pr_title_9a2e3b_idx',
        ),
        migrations.RenameIndex(
            model_name='scrapedlisting',
            new_name='products_sc_product_ec150b_idx',
            old_name='products_sc_product_7d1c2e_idx',
        ),
        migrations.RenameIndex(
            model_name='scrapedlisting',
            new_name='products_sc_last_sc_332389_idx',
            old_name='products_sc_last_sc_8e4f1a_idx',
        ),
    ]
