# Generated by Django 6.0.1 on 2026-06-25 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_products_pr_created_4b8f0d_idx_products_pr_created_bce1a7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('author_role', models.CharField(blank=True, help_text="Short label shown under the name, e.g. 'Smart Shopper'.", max_length=80)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('body', models.TextField(help_text='The review / testimonial text.')),
                ('highlight_label', models.CharField(blank=True, help_text="Optional metric label, e.g. 'Saved'.", max_length=40)),
                ('highlight_value', models.CharField(blank=True, help_text="Optional metric value, e.g. 'Rs. 12,000'.", max_length=40)),
                ('is_published', models.BooleanField(default=True)),
                ('is_sample', models.BooleanField(default=False, help_text='Marks demo/sample reviews so they can be cleared later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
